brace_style = "SameLineWhere"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
max_width = 100
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
