[ucd]
version = "10.0.0"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/DerivedAge.txt"
dest = "data/ucd/DerivedAge.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/DerivedNormalizationProps.txt"
dest = "data/ucd/DerivedNormalizationProps.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/ReadMe.txt"
dest = "data/ucd/ReadMe.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/UnicodeData.txt"
dest = "data/ucd/UnicodeData.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/PropList.txt"
dest = "data/ucd/PropList.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/BidiCharacterTest.txt"
dest = "data/ucd/test/BidiCharacterTest.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/BidiTest.txt"
dest = "data/ucd/test/BidiTest.txt"

[[ucd.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/extracted/DerivedDecompositionType.txt"
dest = "data/ucd/test/DecompositionTypeTest.txt"

[normal]
version = "10.0.0"

[[normal.resources]]
url = "http://www.unicode.org/Public/{version}/ucd/NormalizationTest.txt"
dest = "data/ucd/test/NormalizationTest.txt"

[idna]
version = "10.0.0"

[[idna.resources]]
url = "http://www.unicode.org/Public/idna/{version}/IdnaMappingTable.txt"
dest = "data/idna/IdnaMappingTable.txt"

[[idna.resources]]
url = "http://www.unicode.org/Public/idna/{version}/ReadMe.txt"
dest = "data/idna/ReadMe.txt"

[[idna.resources]]
url = "http://www.unicode.org/Public/idna/{version}/IdnaTest.txt"
dest = "data/idna/test/IdnaTest.txt"
