# For now, crates with tables we can't generate are commented out
---
unic:
  - "unic-bidi"
  - "unic-idna"
  - "unic-normal"
  - "unic-ucd"
unic-idna:
  - "unic-idna-mapping"
  - "unic-idna-punycode"
unic-ucd:
  - "unic-ucd-age"
  - "unic-ucd-bidi"
  - "unic-ucd-core"
  - "unic-ucd-category"
  - "unic-ucd-normal"
  - "unic-ucd-utils"
