[package]
name = "unic-ucd-normal"
version = "0.5.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
keywords = ["text", "unicode", "normalization"]
description = "UNIC - Unicode Character Database - Normalization Properties"
categories = ["text-processing", "parsing", "rendering"]

# No tests/benches that depends on /data/
exclude = ["tests/conformance_tests.rs"]

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }

[dependencies]
unic-ucd-core = { path = "../core/", version = "0.5.0" }
unic-ucd-category = { path = "../category/", version = "0.5.0", optional = true }
unic-utils = { path = "../../utils/", version = "0.5.0" }

[dev-dependencies]
unic-utils = { path = "../../utils", version = "0.5.0" }
unic-ucd-category = { path = "../category/", version = "0.5.0" }

[features]
default = []
