[package]
name = "unic-ucd-category"
version = "0.6.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC - Unicode Character Database - General Category"
keywords = ["text", "unicode", "character-property", "category"]
categories = ["internationalization", "text-processing", "parsing", "rendering"]

# No tests/benches that depends on /data/
exclude = []

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }

[dependencies]
matches = "0.1"
unic-char-property = { path = "../../char/property/", version = "0.6.0" }
unic-char-range = { path = "../../char/range", version = "0.6.0" }
unic-ucd-core = { path = "../core/", version = "0.6.0" }
unic-utils = { path = "../../utils/", version = "0.6.0" }
