[package]
name = "unic-gen"
version = "0.1.0"
authors = ["The UNIC Project Developers"]
homepage = "https://github.com/behnam/rust-unic/"
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC - Unicode Character Database - Table Generation"
publish = false

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }

[dependencies]
getopts = "0.2"

futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"

serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
