[package]
name = "unic-gen"
version = "0.0.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC - Table Generation"
publish = false

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }

[dependencies]
unic-char-range = { path = "../unic/char/range/", version = "0.6.0" }

# Command line argument parsing
clap = "2.25"

# Memoization
lazy_static = "0.2"

# Parsing
itertools = "0.6"
matches = "0.1"
regex = "0.2"
