[package]
name = "unic-gen"
version = "0.0.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC - Table Generation"
publish = false

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }

[dependencies]
unic-char-range = { path = "../unic/char/range/", version = "0.6.0" }

# Command line argument parsing
clap = "2.25"

# Download Unicode files from the web
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"

# Config parsing
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

# Memoization
lazy_static = "0.2"

# Parsing
matches = "0.1"
regex = "0.2"
